# Generated by Django 5.0.6 on 2025-02-02 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenoms', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cni', models.ImageField(upload_to='cni/')),
                ('telephone', models.CharField(max_length=15)),
                ('ville', models.TextField()),
                ('mdp', models.CharField(max_length=255)),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='TontineApp.statut')),
            ],
        ),
    ]
